### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by NguyenDangBinh** [jeya-maria-jose/Medical-Transformer#32]
dear all,
I use GTX 2080Ti to train.
I had the problem below: imgsize = 512
How to solve that?
(pytorch_unet) D:\6449 EBC\segmentation\Medical-Transformer-main>python train.py --train_dataset "data_6449_big/train" --val_dataset "data_6449_big/testB" --direc 'result' --batch_size 1 --epoch 200 --save_freq 10 --modelname "gatedaxialunet" --learning_rate 0.001 --imgsize 512 --gray "no"
Total_params: 1360642
Traceback (most recent call last):
  File "train.py", line 140, in <module>
    output = model(X_batch)
  File "C:\Users\USER\anaconda3\envs\pytorch_unet\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\6449 EBC\segmentation\Medical-Transformer-main\lib\models\axialnet.py", line 507, in forward
    return self._forward_impl(x)
  File "D:\6449 EBC\segmentation\Medical-Transformer-main\lib\models\axialnet.py", line 487, in _forward_impl
    x2 = self.layer2(x1)
  File "C:\Users\USER\anaconda3\envs\pytorch_unet\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\USER\anaconda3\envs\pytorch_unet\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\USER\anaconda3\envs\pytorch_unet\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\6449 EBC\segmentation\Medical-Transformer-main\lib\models\axialnet.py", line 331, in forward
    out = self.hight_block(out)
  File "C:\Users\USER\anaconda3\envs\pytorch_unet\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\6449 EBC\segmentation\Medical-Transformer-main\lib\models\axialnet.py", line 166, in forward
    stacked_similarity = torch.cat([qk, qr, kr], dim=1)
RuntimeError: CUDA out of memory. Tried to allocate 1.50 GiB (GPU 0; 11.00 GiB total capacity; 6.74 GiB already allocated; 777.94 MiB free; 8.13 GiB reserved in total by PyTorch)

**Comment by jeya-maria-jose** [comment]
#17
