### ISSUE TITLE
How to use test.py?

### ISSUE THREAD

**Issue by NguyenDangBinh** [jeya-maria-jose/Medical-Transformer#33]
dear @jeya-maria-jose,
Can you help me,
I had problem about test.py below:
(medt) D:\segmentation\Medical-Transformer-main>python test.py --loaddirec "resultfinal_model.pth" --val_dataset "data_6449_s256/test" --direc '290/gatedaxialunet.pth' --batch_size 1 --modelname "gatedaxialunet" --imgsize 256 --gray "no"
None
Traceback (most recent call last):
  File "test.py", line 82, in <module>
    train_dataset = ImageToImage2D(args.train_dataset, tf_train)
  File "D:\segmentation\Medical-Transformer-main\utils.py", line 131, in __init__
    self.input_path = os.path.join(dataset_path, 'img')
  File "C:\Users\DELL\anaconda3\envs\medt\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by NguyenDangBinh** [comment]
dear @jeya-maria-jose,
Why are you still load the path of dataset in test.py?


" self.input_path = os.path.join(dataset_path, 'img') "
