### ISSUE TITLE
ｗｈｅｎ　ｉ　ｒｕｎ　ｔｈｅ　ｃｏｍｍａｎｄ　ｔｈａｔ　python train.py --train_dataset "E:\Medical-Transformer-main\datasets\train" --val_dataset "E:\Medical-Transformer-main\datasets\val" --direc 'E:\Medical-Transformer-main\path' --batch_size 4 --epoch 400 --save_freq 10 --modelname "gatedaxialunet" --learning_rate 0.001 --imgsize 128 --gray "no"　，An error is displayed as follows:

### ISSUE THREAD

**Issue by 123xu223** [jeya-maria-jose/Medical-Transformer#44]
Total_params: 1326850
Traceback (most recent call last):
  File "train.py", line 130, in <module>
    for batch_idx, (X_batch, y_batch, *rest) in enumerate(dataloader):
  File "D:\anaconda1\envs\Medical-transformer\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "D:\anaconda1\envs\Medical-transformer\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda1\envs\Medical-transformer\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda1\envs\Medical-transformer\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Medical-Transformer-main\utils.py", line 156, in __getitem__
    mask[mask<=127] = 0
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

How does the author solve this error report? Is it a problem of data set processing? How to solve it？

**Comment by Agigina** [comment]
你是不是数据集用的不是png格式的呀，我之前用的jpg格式就报了这个错，改成png格式就好了（但是报别的错嘤

**Comment by 123xu223** [comment]
> 你是不是数据集用的不是png格式的呀，我之前用的jpg格式就报了这个错，改成png格式就好了（但是报别的错嘤

能加个您的邮箱，方便沟通交流吗？

**Comment by 123xu223** [comment]
> > 你是不是数据集用的不是png格式的呀，我之前用的jpg格式就报了这个错，改成png格式就好了（但是报别的错嘤
> 
> 能加个您的邮箱，方便沟通交流吗？

我的邮箱是2536497516@qq.com

**Comment by jeya-maria-jose** [comment]
I think the problem is that the data is not getting loaded. Can you please debug by checking if a single image is loaded from your load directory?

**Comment by honghong6666** [comment]
我的是png格式，还是报错，换了格式解决了没有呀？求助

**Comment by algwang** [comment]
> 我的是png格式，还是报错，换了格式解决了没有呀？求助

您好，请问解决了吗？怎么解决的，盼回复，感谢
